### ISSUE TITLE
dockerfile requires dist folder, but is ignored in .gitignore

### ISSUE THREAD

**Issue by avandermeer** [gswrx/nestjs-backend-boilerplate#6]

**Comment by avandermeer** [comment]
proposed solution: add in dockerfile:

```
npm ci
```

**Comment by christianversloot** [comment]
Could you please describe why this is a problem with the deployment methodology you're using?

**Comment by christianversloot** [comment]
https://github.com/gswrx/nestjs-backend-boilerplate/commit/2b84af1de60ae6749eb161444e4387be4e29d4ff
